In [3]:
import numpy as np

In [13]:
mylist = list([1,2,3,4])

In [14]:
mylist

[1, 2, 3, 4]

In [6]:
myarray = np.array([1,2,3,4])

In [8]:
myarray

array([1, 2, 3, 4])

In [9]:
new = myarray/2

In [10]:
new

array([0.5, 1. , 1.5, 2. ])

In [15]:
new_list = mylist/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [16]:
type(myarray)

numpy.ndarray

In [17]:
type(mylist)

list

In [18]:
# Creating an array
import numpy as np
myarray = np.array([1,2,3,4,5,6])
print(myarray)

[1 2 3 4 5 6]


In [19]:
type(myarray)

numpy.ndarray

In [29]:
# 0-Dimensional array
myarray0 = np.array(40)

In [30]:
print(myarray0)

40


In [31]:
type(myarray0)

numpy.ndarray

In [32]:
# 1- Dimension array
myarray1 = np.array([1,2,3])
print(myarray1)

[1 2 3]


In [33]:
# 2- Dimension array
myarray2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarray2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [50]:
# 3- Dimensional array
myarray3 = np.array([[[1,2],[4,5]],[[1,2],[2,5]]])
print(myarray3)

[[[1 2]
  [4 5]]

 [[1 2]
  [2 5]]]


In [51]:
type(myarray3)

numpy.ndarray

In [52]:
# Dimension of arrays
print(myarray3.ndim)

3


In [53]:
print(myarray2.ndim)

2


In [54]:
print(myarray1.ndim)

1


In [55]:
print(myarray0.ndim)

0


In [59]:
# Higher dimension

myarray = np.array([1,2,3,4,5],ndmin=5)
print(myarray)

[[[[[1 2 3 4 5]]]]]


In [60]:
## Accessing the elements

print(myarray1)

[1 2 3]


In [62]:
myarray1[1]

2

In [63]:
print(myarray2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [64]:
print(myarray2[2, 1])

8


In [67]:
print(myarray1[-1])

3


In [69]:
print(myarray3)

[[[1 2]
  [4 5]]

 [[1 2]
  [2 5]]]


In [70]:
print(myarray3[1, 0, 1])

2


In [71]:
print(myarray3[0,0,1])

2


In [68]:
# Slicing [start:stop:step]

In [73]:
myarray1

array([1, 2, 3])

In [76]:
print(myarray1[1:])

[2 3]


In [78]:
print(myarray1[::-1])

[3 2 1]


In [79]:
print(myarray1[::2])

[1 3]


In [80]:
myarray2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
print(myarray2[0:3,1])

[2 5 8]


In [85]:
print(myarray2[1: ,])

[[4 5 6]
 [7 8 9]]


In [88]:
print(myarray2[ : ,1:])

[[2 3]
 [5 6]
 [8 9]]


In [82]:
print(myarray2[1: , 1: ])

[[5 6]
 [8 9]]


In [89]:
## Special arrays

In [90]:
myarray = np.arange(10)

In [91]:
myarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
myarray = np.zeros(3)

In [93]:
print(myarray)

[0. 0. 0.]


In [97]:
myarray = np.zeros((2,3))

In [98]:
myarray

array([[0., 0., 0.],
       [0., 0., 0.]])

In [99]:
myarray = np.ones((2,3))

In [100]:
myarray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [101]:
myarray = np.eye(3)

In [102]:
myarray

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [103]:
myarray = np.linspace(1,5,10)

In [104]:
myarray

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [105]:
myarray.ndim

1

In [106]:
myarray = np.linspace(1,10,10)

In [107]:
myarray

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [110]:
myarray = np.linspace(1,10,6)

In [111]:
myarray

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [112]:
# reshaping
myarray = np.eye(4)

In [113]:
myarray

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [114]:
myarray.reshape((2,8))

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [116]:
myarray.reshape((2,9))

ValueError: cannot reshape array of size 16 into shape (2,9)

In [117]:
myarray.reshape(16)

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])