In [1]:
import numpy as np

In [7]:
myarray = np.array([[3],[4]])

In [8]:
myarray.shape

(2, 1)

In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr1 = arr.reshape(2, 4)
# print(arr1.base)
arr1.base

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [19]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:1, ::2]):
  print(x)

1
3


In [23]:
import numpy as np

arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],[[1, 2, 3, 4], [5, 6, 7, 8]]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 0, 3) 4
(1, 1, 0) 5
(1, 1, 1) 6
(1, 1, 2) 7
(1, 1, 3) 8


In [27]:
import numpy as np

arr1 = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]]])

arr2 = np.array([[[5, 6], [7, 8]],[[5, 6], [7, 8]]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[1 2]
  [3 4]
  [5 6]
  [7 8]]]
