In [1]:
import numpy as np

In [28]:
## Copy Vs View

In [39]:
arr = np.array([1,2,3,4,5])
myarray = arr.copy()
# myarray[0] = 42
arr[0] = 10
print('arr:', arr)
print('myarray:', myarray)

arr: [10  2  3  4  5]
myarray: [1 2 3 4 5]


In [44]:
arr = np.array([1,2,3,4,5])
myarray = arr.view()
myarray[0] = 40
arr[0] = 10
print('arr:', arr)
print('myarray:', myarray)

arr: [10  2  3  4  5]
myarray: [10  2  3  4  5]


In [45]:
print(myarray.base)

[10  2  3  4  5]


In [46]:
print(arr.base)

None


In [47]:
arr = np.array([1,2,3,4,5])
myarray = arr.copy()
print(myarray.base)

None


In [48]:
## Shape

In [52]:
arr = np.array(10)
print(arr.shape)

()


In [53]:
arr1 = np.array([1,2,3,4,5])
print(arr1.shape)

(5,)


In [55]:
arr2 = np.array([[1,2],[3,5]])
print(arr2.shape)

(2, 2)


In [58]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[1,2,3],[4,5,6]]])
print(arr3.shape)

(2, 2, 3)


In [60]:
arrn = np.array([1,2,3], ndmin=5)
print(arrn)
print(arrn.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


In [61]:
## reshape

In [62]:
arr = np.array([[[1,2],[4,5]], [[1,2],[4,5]]])
print(arr)

[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]


In [63]:
arr.reshape(2,4)

array([[1, 2, 4, 5],
       [1, 2, 4, 5]])

In [65]:
arr.reshape(3,4)

ValueError: cannot reshape array of size 8 into shape (3,4)

In [67]:
myarray = arr.reshape(8)
print(myarray)

[1 2 4 5 1 2 4 5]


In [68]:
print(myarray.base)

[[[1 2]
  [4 5]]

 [[1 2]
  [4 5]]]


In [69]:
arr.reshape(2,2,2)

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [70]:
arr.reshape(2,-1)

array([[1, 2, 4, 5],
       [1, 2, 4, 5]])

In [75]:
arr.reshape(-1,2,2)  ### (x * 2 * 2 = 8 =>  x = 2)

array([[[1, 2],
        [4, 5]],

       [[1, 2],
        [4, 5]]])

In [76]:
arr.reshape(-1)

array([1, 2, 4, 5, 1, 2, 4, 5])

In [77]:
## iterating arrays

In [83]:
myarray = np.array([1,2,3])
myarray2 = np.array([[1,2,3],[4,5,6]])
myarray3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [79]:
for x in myarray:
    print(x)

1
2
3


In [81]:
for x in myarray2:
    print(x)

[1 2 3]
[4 5 6]


In [82]:
for x in myarray2:
    for y in x:
        print(y)

1
2
3
4
5
6


In [85]:
for x in myarray3:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]


In [86]:
for x in myarray3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
1
2
3
4
5
6


In [89]:
for x in np.nditer(myarray3):
    print(x)

1
2
3
4
5
6
1
2
3
4
5
6


In [91]:
print(myarray2)

[[1 2 3]
 [4 5 6]]


In [93]:
for x in np.nditer(myarray2[ 1: , ::2]):
    print(x)

4
6


In [96]:
for idx, x in np.ndenumerate(myarray2):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [98]:
for idx, x in np.ndenumerate(myarray):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [99]:
print(myarray3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [102]:
for x in np.nditer(myarray3[:1,1:,::2]):
    print(x)

4
6


In [103]:
for idx, x in np.ndenumerate(myarray3):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 1
(1, 0, 1) 2
(1, 0, 2) 3
(1, 1, 0) 4
(1, 1, 1) 5
(1, 1, 2) 6
