In [1]:
import numpy as np

In [ ]:
## Join

In [3]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [4]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([5,6])
arr = np.concatenate((arr1, arr2))
print(arr)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

(rows, columns) ---> (2,3) --> (0,1) -->
axis = 0 --> rows
axis = 1 --> columns

In [7]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [8]:
# stack

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis =1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.stack((arr1, arr2))
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [13]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis =1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [14]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr1, arr2), axis =0)
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.concatenate((arr2, arr1), axis =0)
print(arr)

[[5 6]
 [7 8]
 [1 2]
 [3 4]]


In [16]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])
arr = np.stack((arr2, arr1), axis =0)
print(arr)

[[[5 6]
  [7 8]]

 [[1 2]
  [3 4]]]


In [21]:
arr1 = np.array([[11,12], [13,14]])
arr2 = np.array([[15,16], [17,18]])
arr = np.hstack((arr1, arr2))
print(arr)

[[11 12 15 16]
 [13 14 17 18]]


In [22]:
arr1 = np.array([[11,12], [13,14]])
arr2 = np.array([[15,16], [17,18]])
arr = np.vstack((arr1, arr2))
print(arr)

[[11 12]
 [13 14]
 [15 16]
 [17 18]]


In [20]:
arr1 = np.array([[11,12], [13,14]])
arr2 = np.array([[15,16], [17,18]])
arr = np.stack((arr1, arr2))
print(arr)

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]


In [19]:
arr1 = np.array([[11,12], [13,14]])
arr2 = np.array([[15,16], [17,18]])
arr = np.concatenate((arr1, arr2))
print(arr)

[[11 12]
 [13 14]
 [15 16]
 [17 18]]


In [23]:
## Splitting

In [26]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 2)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6])]


In [27]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [30]:
arr2 = np.array([[9,8],[7,6],[5,4],[3,2]])
newarr = np.array_split(arr2, 5)
print(newarr)

[array([[9, 8]]), array([[7, 6]]), array([[5, 4]]), array([[3, 2]]), array([], shape=(0, 2), dtype=int64)]


In [31]:
arr2 = np.array([[9,8],[7,6],[5,4],[3,2]])
newarr = np.array_split(arr2, 4, axis=1)
print(newarr)

[array([[9],
       [7],
       [5],
       [3]]), array([[8],
       [6],
       [4],
       [2]]), array([], shape=(4, 0), dtype=int64), array([], shape=(4, 0), dtype=int64)]


In [35]:
arr3 = np.array([[9,8,7],[5,4,3]])
newarr = np.array_split(arr3, 4, axis=1)
print(newarr)

[array([[9],
       [5]]), array([[8],
       [4]]), array([[7],
       [3]]), array([], shape=(2, 0), dtype=int64)]


In [36]:
## Searching

In [37]:
arr = np.array([1,2,3,4,5,6])
new = np.where(arr == 4)
print(new)

(array([3]),)


In [38]:
arr = np.array([1,2,3,4,4,6])
new = np.where(arr == 4)
print(new)

(array([3, 4]),)


In [41]:
arr = np.array([[1,2],[3,4]])
new = np.where(arr == 4)
print(new)
#(1,1)

(array([1]), array([1]))


In [42]:
arr = np.array([1,2,3,4])
new = np.searchsorted(arr, 3)
print(new)

2


In [45]:
arr = np.array([1,2,3,4])
new = np.searchsorted(arr, 6)
print(new)

4


In [46]:
arr = np.array([1,4,7,9])
new = np.searchsorted(arr, 6)
print(new)

2


In [47]:
arr = np.array([1,4,7,9])
new = np.searchsorted(arr, [6,3,8])
print(new)

[2 1 3]


In [52]:
arr = np.array([1,4,7,9])
new = np.searchsorted(arr, 7, side='right')
print(new)

3


In [64]:
arr = np.array([1, 4, 7, 9])
x = np.searchsorted(arr, 5, side='right')
print(x)

2


In [60]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [65]:
# Sorting

In [66]:
arr = np.array([6, 10, 8, 12])
x = np.sort(arr)
print(x)

[ 6  8 10 12]


In [67]:
arr = np.array([[6, 10, 8, 12],[2,1,6,4]])
x = np.sort(arr)
print(x)

[[ 6  8 10 12]
 [ 1  2  4  6]]


In [68]:
arr = np.array(["A","E","B"])
x = np.sort(arr)
print(x)

['A' 'B' 'E']


In [69]:
arr = np.array([True, False, True])
x = np.sort(arr)
print(x)

[False  True  True]
